### ISSUE TITLE
Script doesn't do anything

### ISSUE THREAD

**Issue by TobiasDeBruijn** [Matoking/NVIDIA-vBIOS-VFIO-Patcher#12]
Hello!

When I run `python3 nvidia_vbios_vfio_patcher.py -i NVIDIA.GTX1070.8192.160520.bin -o patched.bin` in cmd, I get no result. Same goes when I run it with `python` instead of `python3`

Screenshot:
![image](https://user-images.githubusercontent.com/28569170/77580632-a3e86b80-6edc-11ea-92c6-57bfb46aa452.png)

Am I doing something stupidly wrong or? Windows 10 by the way

**Comment by Marvo2011** [comment]
Hello

I think you should run it under Linux.
